name: CI-CD Pipeline

on:
  push:
    branches: [ 'main', 'dev' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.PAT }}

      - name: Set Docker tag suffix
        id: set_tag
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "suffix=prod" >> $GITHUB_OUTPUT
          else
            # Sanitize branch name to be a valid Docker tag
            echo "suffix=$(echo ${{ github.ref_name }} | sed 's/[^a-zA-Z0-9.-]/-/g')" >> $GITHUB_OUTPUT
          fi

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-${{ steps.set_tag.outputs.suffix }}:latest
          load: true

      - name: Test container startup
        run: |
          docker run -d --rm --name test-run ghcr.io/${{ github.repository }}-${{ steps.set_tag.outputs.suffix }}:latest
          echo "Waiting for container to start..."
          sleep 15
          echo "Checking container logs:"
          docker logs test-run
          echo "Checking container status:"
          if ! docker ps -f "name=test-run" --format '{{.Names}}' | grep -q test-run; then
            echo "Container failed to start or crashed."
            exit 1
          else
            echo "Container is running. Test passed."
            docker stop test-run
          fi