name: CI-CD Pipeline

on:
  push:
    branches: [ 'main', 'dev' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.PAT }}

      - name: Set Docker tag suffix
        id: set_tag
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "suffix=prod" >> $GITHUB_OUTPUT
          else
            # Sanitize branch name to be a valid Docker tag
            echo "suffix=$(echo ${{ github.ref_name }} | sed 's/[^a-zA-Z0-9.-]/-/g')" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and test startup
        run: |
          npm install
          echo "Attempting to start the application for a smoke test..."
          MONGO_URI="mongodb://test-mongo:27017/psfAuth" \
          SQS_REQUESTS_QUEUE="dummy-queue" \
          npm run start &
          PID=$!
          sleep 15
          if ps -p $PID > /dev/null; then
            echo "Application started successfully. Test passed."
            kill $PID
          else
            echo "Application failed to start or crashed."
            exit 1
          fi

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-${{ steps.set_tag.outputs.suffix }}:latest